import Head from 'next/head'
import About from '../components/About'
import Header from '../components/Header'
import HomePage from '../components/Home'
import Pricing from '../components/Pricing'
import Services from '../components/Services'

import Script from 'next/script'
import Testimonial from '../components/Testimonial'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Digital web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <div>

        {/* have to fixed the scrooly and make responsive home,about and services */}

        <Header />
        <HomePage />
        <About />
        <Services />
        <Pricing />
        <Testimonial />
        <Footer />
      </div>

      <Script src="https://kit.fontawesome.com/a076d05399.js"></Script>
    </div>

  )
}
